CREATE TABLE USERS
(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR(50) NOT NULL,
    NAME VARCHAR(50) NOT NULL
);
CREATE TABLE SETTINGS
(
	USER_ID BIGINT NOT NULL,
    SETTING VARCHAR(40) NOT NULL,
    VALUE VARCHAR(40),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);
CREATE TABLE ACCOUNTS
(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
	NAME VARCHAR(50) NOT NULL,
    UNIQUE(NAME),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);
CREATE TABLE TYPES
(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
	NAME VARCHAR(50) NOT NULL,
    UNIQUE(NAME),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);
CREATE TABLE EXPENSES
(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	COST INTEGER NOT NULL,
	FREQUENCY VARCHAR(10) NOT NULL,
	STARTED DATE NOT NULL,
	AUTOMATIC TINYINT NOT NULL DEFAULT 0,
	ACCOUNT_ID BIGINT,
	TYPE_ID BIGINT NOT NULL DEFAULT 1,
    UNIQUE(NAME),
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(ID),
    FOREIGN KEY (TYPE_ID) REFERENCES TYPES(ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);
CREATE TABLE TRANSACTIONS
(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
	AMOUNT INTEGER NOT NULL,
	COMMENT VARCHAR(500),
	ACCOUNT_ID BIGINT NOT NULL DEFAULT 1,
	TYPE_ID BIGINT NOT NULL DEFAULT 1,
	EXPENSE_ID BIGINT NOT NULL DEFAULT 1,
	DATE DATE NOT NULL,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(ID),
    FOREIGN KEY (TYPE_ID) REFERENCES TYPES(ID),
	FOREIGN KEY (EXPENSE_ID) REFERENCES EXPENSES(ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);